Running tests under Python 3.9.18: /home/jmw/anaconda3/envs/vct_tf/bin/python
[ RUN      ] ModelsTest.test_session
[  SKIPPED ] ModelsTest.test_session
[ RUN      ] ModelsTest.test_train_eval
INFO:tensorflow:time(__main__.ModelsTest.test_train_eval): 0.84s
I1121 13:45:28.266117 140326674604416 test_util.py:2460] time(__main__.ModelsTest.test_train_eval): 0.84s
[  FAILED  ] ModelsTest.test_train_eval
======================================================================
ERROR: test_train_eval (__main__.ModelsTest)
ModelsTest.test_train_eval
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jmw/ing/myfi/vfi/src/models_test.py", line 70, in test_train_eval
    model= Model(feature_extractor(**feature_extractor_cfg), **flow_estimation_cfg)
  File "/home/jmw/ing/myfi/vfi/src/model.py", line 274, in __init__
    self.optimizer = tf.keras.optimizers.Adamw(learning_rate= self.learning_rate_schedule)
AttributeError: module 'tensorflow.keras.optimizers' has no attribute 'Adamw'
----------------------------------------------------------------------
Ran 2 tests in 0.842s
FAILED (errors=1, skipped=1)