Running tests under Python 3.9.18: /home/jmw/anaconda3/envs/vct_tf/bin/python
[ RUN      ] ModelsTest.test_session
[  SKIPPED ] ModelsTest.test_session
[ RUN      ] ModelsTest.test_train_eval
INFO:tensorflow:time(__main__.ModelsTest.test_train_eval): 0.9s
I1121 16:03:29.821760 140105523171712 test_util.py:2460] time(__main__.ModelsTest.test_train_eval): 0.9s
[  FAILED  ] ModelsTest.test_train_eval
======================================================================
ERROR: test_train_eval (__main__.ModelsTest)
ModelsTest.test_train_eval
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jmw/ing/myfi/vfi/src/models_test.py", line 86, in test_train_eval
    model.load_ckpt(path=args.resume)
  File "/home/jmw/ing/myfi/vfi/src/model.py", line 285, in load_ckpt
    print('load a checkpoint at'+ str(path) + 'for' + manager.latest_checkpoint)
TypeError: can only concatenate str (not "NoneType") to str
----------------------------------------------------------------------
Ran 2 tests in 0.904s
FAILED (errors=1, skipped=1)
resume /home/jmw/ing/myfi/vfi/ckpt