Running tests under Python 3.9.18: /home/jmw/anaconda3/envs/vct_tf/bin/python
[ RUN      ] ModelsTest.test_session
[  SKIPPED ] ModelsTest.test_session
[ RUN      ] ModelsTest.test_train_eval
  0%|                                                                                                                                                         | 0/60 [00:02<?, ?batch/s]
INFO:tensorflow:time(__main__.ModelsTest.test_train_eval): 3.41s
I1121 14:46:53.618737 140190770884992 test_util.py:2460] time(__main__.ModelsTest.test_train_eval): 3.41s
[  FAILED  ] ModelsTest.test_train_eval
======================================================================
ERROR: test_train_eval (__main__.ModelsTest)
ModelsTest.test_train_eval
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jmw/ing/myfi/vfi/src/models_test.py", line 91, in test_train_eval
    metrics=train_step(img0,gt,img1)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 141, in error_handler
    return fn(*args, **kwargs)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 915, in __call__
    result = self._call(*args, **kwds)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 963, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 785, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 2523, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 2760, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 2670, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py", line 1247, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 677, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py", line 1233, in autograph_handler
    raise e.ag_error_metadata.to_exception(e)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py", line 1222, in autograph_handler
    return autograph.converted_call(
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 439, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/tmp/__autograph_generated_filen3l1xm1b.py", line 11, in tf__train_step
    (pred, metric) = ag__.converted_call(ag__.ld(self).interpolator, (ag__.ld(img0), ag__.ld(gt), ag__.ld(img1)), None, fscope)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 441, in converted_call
    result = converted_f(*effective_args)
  File "/tmp/__autograph_generated_filezhk7fz6m.py", line 17, in tf__interpolator
    (af, mf) = ag__.converted_call(ag__.ld(self).feature_estimation, (ag__.ld(img0), ag__.ld(img1)), None, fscope)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 441, in converted_call
    result = converted_f(*effective_args)
  File "/tmp/__autograph_generated_filed5hi1ld8.py", line 107, in tf____call__
    ag__.for_stmt(ag__.converted_call(ag__.ld(range), (ag__.ld(self).num_stages,), None, fscope), None, loop_body_1, get_state_4, set_state_4, ('x',), {'iterate_names': 'i'})
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/operators/control_flow.py", line 463, in for_stmt
    _py_for_stmt(iter_, extra_test, body, None, None)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/operators/control_flow.py", line 512, in _py_for_stmt
    body(target)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/operators/control_flow.py", line 478, in protected_body
    original_body(protected_iter)
  File "/tmp/__autograph_generated_filed5hi1ld8.py", line 96, in loop_body_1
    ag__.if_stmt(ag__.ld(i) < ag__.ld(self).conv_stages, if_body_2, else_body_2, get_state_3, set_state_3, ('motion_features[i]', 'x'), 2)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/operators/control_flow.py", line 1363, in if_stmt
    _py_if_stmt(cond, body, orelse)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/operators/control_flow.py", line 1416, in _py_if_stmt
    return body() if cond else orelse()
  File "/tmp/__autograph_generated_filed5hi1ld8.py", line 92, in else_body_2
    ag__.for_stmt(ag__.ld(block), None, loop_body, get_state_2, set_state_2, ('x',), {'iterate_names': 'blk'})
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/operators/control_flow.py", line 463, in for_stmt
    _py_for_stmt(iter_, extra_test, body, None, None)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/operators/control_flow.py", line 512, in _py_for_stmt
    body(target)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/operators/control_flow.py", line 478, in protected_body
    original_body(protected_iter)
  File "/tmp/__autograph_generated_filed5hi1ld8.py", line 89, in loop_body
    (x, x_motion) = ag__.converted_call(ag__.ld(blk), (ag__.ld(x), ag__.ld(cor), ag__.ld(H), ag__.ld(W), 2 * ag__.ld(B)), None, fscope)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 377, in converted_call
    return _call_unconverted(f, args, kwargs, options)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 459, in _call_unconverted
    return f(*args)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 61, in error_handler
    return fn(*args, **kwargs)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/keras/engine/base_layer.py", line 1097, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 155, in error_handler
    raise new_e.with_traceback(e.__traceback__) from None
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 96, in error_handler
    return fn(*args, **kwargs)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 692, in wrapper
    raise e.ag_error_metadata.to_exception(e)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 689, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 439, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/tmp/__autograph_generated_file789d_u_p.py", line 11, in tf__call
    (x_pad, mask) = ag__.converted_call(ag__.ld(pad_if_needed), (ag__.ld(x), ag__.ld(self).window_size), None, fscope)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 441, in converted_call
    result = converted_f(*effective_args)
  File "/tmp/__autograph_generated_filecmzojvhy.py", line 83, in tf__pad_if_needed
    ag__.if_stmt(ag__.or_(lambda : ag__.ld(pad_h) > 0, lambda : ag__.ld(pad_w) > 0), if_body, else_body, get_state_2, set_state_2, ('do_return', 'retval_', 'h', 'w'), 2)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/operators/control_flow.py", line 1363, in if_stmt
    _py_if_stmt(cond, body, orelse)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/operators/control_flow.py", line 1416, in _py_if_stmt
    return body() if cond else orelse()
  File "/tmp/__autograph_generated_filecmzojvhy.py", line 23, in if_body
    img_mask = ag__.converted_call(ag__.ld(np).zeros, ([1, ag__.ld(h) + ag__.ld(pad_h), ag__.ld(w) + ag__.ld(pad_w), 1], ag__.ld(tf).float32), None, fscope)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 371, in converted_call
    return py_builtins.overload_of(f)(*args)
TypeError: in user code:
    File "/home/jmw/ing/myfi/vfi/src/model.py", line 261, in train_step  *
        pred,metric = self.interpolator(img0,gt,img1)
    File "/home/jmw/ing/myfi/vfi/src/model.py", line 295, in interpolator  *
        af, mf  = self.feature_estimation(img0, img1) # feature extractor [[2,256,30,60],,...]5개, [[2,256,30,60],...] 3개
    File "/home/jmw/ing/myfi/vfi/src/model.py", line 154, in __call__  *
        x, x_motion  = blk(x, cor, H, W,2*B) #motion former block
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 61, in error_handler  **
        return fn(*args, **kwargs)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/keras/engine/base_layer.py", line 1097, in __call__
        outputs = call_fn(inputs, *args, **kwargs)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 155, in error_handler
        raise new_e.with_traceback(e.__traceback__) from None
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 96, in error_handler
        return fn(*args, **kwargs)
    File "/tmp/__autograph_generated_file789d_u_p.py", line 11, in tf__call  **
        (x_pad, mask) = ag__.converted_call(ag__.ld(pad_if_needed), (ag__.ld(x), ag__.ld(self).window_size), None, fscope)
    File "/tmp/__autograph_generated_filecmzojvhy.py", line 83, in tf__pad_if_needed  **
        ag__.if_stmt(ag__.or_(lambda : ag__.ld(pad_h) > 0, lambda : ag__.ld(pad_w) > 0), if_body, else_body, get_state_2, set_state_2, ('do_return', 'retval_', 'h', 'w'), 2)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/operators/control_flow.py", line 1363, in if_stmt
        _py_if_stmt(cond, body, orelse)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/operators/control_flow.py", line 1416, in _py_if_stmt
        return body() if cond else orelse()
    File "/tmp/__autograph_generated_filecmzojvhy.py", line 23, in if_body
        img_mask = ag__.converted_call(ag__.ld(np).zeros, ([1, ag__.ld(h) + ag__.ld(pad_h), ag__.ld(w) + ag__.ld(pad_w), 1], ag__.ld(tf).float32), None, fscope)
    TypeError: Exception encountered when calling layer "motion_former_block_2" "                 f"(type MotionFormerBlock).
    in user code:
        File "/home/jmw/ing/myfi/vfi/src/modules.py", line 312, in call  *
            x_pad, mask = pad_if_needed(x,  self.window_size)
        File "/home/jmw/ing/myfi/vfi/src/modules.py", line 229, in pad_if_needed  *
            img_mask = (np.zeros([1, h+pad_h, w+pad_w, 1], tf.float32))
        TypeError: Cannot interpret 'tf.float32' as a data type
    Call arguments received by layer "motion_former_block_2" "                 f"(type MotionFormerBlock):
      • x=tf.Tensor(shape=(128, 448, 256), dtype=float32)
      • cor=tf.Tensor(shape=(128, 16, 28, 2), dtype=float32)
      • H=16
      • W=28
      • B=128
----------------------------------------------------------------------
Ran 2 tests in 3.407s
FAILED (errors=1, skipped=1)