Running tests under Python 3.9.18: /home/jmw/anaconda3/envs/vct_tf/bin/python
[ RUN      ] ModelsTest.test_session
[  SKIPPED ] ModelsTest.test_session
[ RUN      ] ModelsTest.test_train_eval
INFO:tensorflow:time(__main__.ModelsTest.test_train_eval): 0.0s
I1121 19:10:49.114306 140134140158336 test_util.py:2460] time(__main__.ModelsTest.test_train_eval): 0.0s
[  FAILED  ] ModelsTest.test_train_eval
======================================================================
ERROR: test_train_eval (__main__.ModelsTest)
ModelsTest.test_train_eval
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jmw/ing/myfi/my_film/src/models_test.py", line 70, in test_train_eval
    model= Model(feature_extractor(**feature_extractor_cfg), **flow_estimation_cfg)
NameError: name 'feature_extractor' is not defined
----------------------------------------------------------------------
Ran 2 tests in 0.001s
FAILED (errors=1, skipped=1)